export const projects = [
  {
    slug: "nepo-games",
    name: "Nepo Games",
    tagline: "Buy and sell game accounts. Safely.",
    stack: [
      "Next.js",
      "JavaScript",
      "Node.js",
      "PostgreSQL",
      "Paystack",
      "Resend",
      "Gemini AI",
      "Tailwind CSS",
    ],
    about:
      "A secure game account marketplace that eliminates peer-to-peer scams using escrow payments, in-app seller chat, and a built-in dispute system.",
    description: [
      "Game account trading is riddled with scams — buyers pay and never receive login details, or receive accounts that don't match the listing. Nepo Games was built to fix that, and I designed and built the entire platform alone, from the database to the UI.",
      "The core protection is escrow: when a buyer pays, the funds are held and not released to the seller until the buyer confirms the login details are correct. The seller is notified to release credentials only after payment is secured. The buyer then gets a 30-minute verification window — the timer doesn't start until they actually open the login details, so no one is rushed unfairly.",
      "If the buyer doesn't respond within 30 minutes of checking the details, the funds are automatically released to the seller. But if there's an issue — wrong credentials, account doesn't match — the buyer can raise a dispute and the transaction is flagged for review.",
      "Beyond the core flow, users get an in-app wallet to fund or withdraw their balance, real-time chat with sellers before committing to a purchase, and an AI-powered contact support system built on Gemini for instant help.",
    ],
    
    highlights: [
      "Escrow payment system — funds held until buyer confirms account access",
      "30-minute buyer verification window that only starts on login detail view",
      "Auto-release to seller if buyer doesn't respond after 30 minutes",
      "Dispute system triggered if buyer reports incorrect credentials",
      "In-app chat — buyers can message sellers before paying",
      "Wallet system with deposit and withdrawal via Paystack",
      "Gemini AI integration powering the contact support chat",
      "Transactional emails via Resend for all key payment events",
      "Built solo — full-stack, frontend and backend",
    ],
    link: "https://nepogames.com",
    github: "https://github.com/Modred14/nepo-games",
    img: "/nepo-games.png",
  },
  {
    slug: "tappay",
    name: "TapPay",
    tagline: "Tap. Pay. Done.",
    stack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Lucide React",
      "PayAza API",
      "NFC",
      "Railway",
    ],
    about:
      "First place winner at Techfest 5.0 — a digital payment app with NFC tap-to-pay, QR scanning, and phone number transfers, shipped in 32 hours.",
    description: [
      "TapPay was built by a 5-person team at Techfest 5.0 (themed Cred, Code & Culture). We shipped both a mobile app and a web analytics dashboard within 32 hours and presented it live at the event — walking away with first place.",
      "My role was frontend: I built the web dashboard and contributed to the app UI using Next.js and TypeScript, while my teammates handled the backend, NFC logic, and PayAza API integration.",
      "The standout feature is NFC tap-to-pay: the sender and receiver simply bring the backs of their phones together to initiate a transfer. For devices without NFC, users can pay via QR code scan or by entering the recipient's phone number — so nobody gets left out.",
      "The web dashboard gives users a real-time view of their spending and balance. It uses live data — no page reload needed. Account funding is handled through the PayAza API, making the full payment loop functional end-to-end.",
    ],
    highlights: [
      "NFC tap-to-pay — bring two phones together to transfer instantly",
      "QR code payments for devices without NFC support",
      "Phone number-based transfers as a third payment option",
      "PayAza API integration for wallet funding and transactions",
      "Real-time web dashboard — balance and spending reflect instantly",
      "Full MVP — mobile app and web platform shipped in 32 hours",
      "First place winner at Techfest 5.0 hackathon",
    ],
    link: "https://tappay.up.railway.app/",
    github: "https://github.com/Missfavis-coder/PayAza/",
    img: "/tappay.png",
  },
  {
    slug: "nexopra",
    name: "Nexopra",
    tagline: "Your AI-powered opportunity scout, on WhatsApp.",
    stack: [
      "Node.js",
      "JavaScript",
      "Baileys",
      "Groq AI",
      "LLaMA 4",
      "Playwright",
      "Devpost API",
      "Greenhouse API",
      "Lever API",
    ],
    about:
      "Nexopra is a WhatsApp bot that delivers curated tech jobs, hackathons, fellowships, and opportunities directly to users.",
    description: [
      "Most opportunity platforms require you to go looking — opening apps, browsing job boards, checking newsletters. Nexopra flips that. It comes to you, directly on WhatsApp, every single day.",
      "Users onboard in under two minutes by selecting their tech field, region, and preferred delivery time. From that point, Nexopra handles everything — scraping Devpost, YC Jobs, Greenhouse, Lever, and Wellfound on a rolling schedule, then filtering results through Groq-powered AI before they ever reach a user.",
      "The AI layer is what separates Nexopra from a simple job feed. Every opportunity is classified for quality, relevance, experience level, and student-friendliness before being matched against each user's profile. Low-signal listings, spam, and duplicates are dropped automatically.",
      "A two-layer deduplication system ensures users never see the same opportunity twice — once globally across the cache, and once per user. On-site and hybrid roles are filtered by region, while remote opportunities are surfaced globally.",
    ],
    highlights: [
      "AI filtering via Groq LLaMA 4 — rejects spam, duplicates, and low-quality listings",
      "Background scheduler — collects jobs every 30 mins, hackathons every 60 mins",
      "Sources: Devpost, YC Jobs, Greenhouse, Lever, Wellfound",
      "Two-layer deduplication — global cache and per-user seen tracking",
      "Region-aware filtering — on-site roles matched to user location",
      "Supports jobs, internships, hackathons, grants, fellowships, and programs",
      "Conversational onboarding and profile management entirely inside WhatsApp",
      "Built solo — full architecture, collectors, AI pipeline, and bot logic",
    ],
    link: "https://nexopra.modred.dev",
    github: "https://github.com/Modred14/Nexopra",
    img: "/nexopra.png",
  },
  {
    slug: "scissors",
    name: "Scissors",
    tagline: "Short links. Big impact.",
    stack: [
      "TypeScript",
      "Vue.js",
      "Node.js",
      "Firebase",
      "Tailwind CSS",
      "Express.js",
      "REST API",
    ],
    about:
      "Scissors is a URL-shortening platform that allows users to generate short, custom URLs and corresponding QR codes.",
    description: [
      "Scissors was born out of a simple frustration: long, ugly links that break in emails and look unprofessional. The goal was to build a clean, fast, and reliable alternative.",
      "The platform lets users shorten any URL, create custom aliases, and generate QR codes on the fly — all with a minimal, distraction-free interface.",
      "Under the hood, Firebase handles real-time persistence and authentication, while the Express.js API manages redirect logic and analytics tracking.",
    ],
    highlights: [
      "Custom alias generation for branded short links",
      "On-demand QR code creation for every shortened URL",
      "Real-time click analytics dashboard",
      "Firebase-backed persistence with instant read/write",
      "Fully responsive — works seamlessly on mobile and desktop",
      "TypeScript throughout for type-safety and maintainability",
    ],
    link: "https://app-scissors.netlify.app/",
    github: "https://github.com/Modred14/Scissors",
    img: "/scissors.png",
  },
  {
    slug: "nacos-oau-feedback",
    name: "Nacos OAU Anonymous Feedback",
    tagline: "Honest voices. Zero identity.",
    stack: ["Next.js", "JavaScript", "PostgreSQL", "Tailwind CSS"],
    about: "A fully anonymous feedback platform for the Nacos OAU Chapter.",
    description: [
      "Student feedback systems usually fail because students don't trust them. Put your name on a form and suddenly you're not being honest — you're being careful. Nacos OAU Anonymous Feedback was built to remove that friction entirely.",
      "There are no accounts, no login screens, and no emails collected from respondents. A visitor lands on the homepage, sees the open questions created by chapter admins, picks one, and types their response. That's it. Nothing is stored except the text itself.",
      "On the admin side, a password-protected dashboard lets chapter executives create, edit, and toggle questions on or off without touching a database. Every response is grouped under its question, with a count, a timestamp, and the ability to delete inappropriate submissions. The password never touches the frontend — it lives only in environment variables and is verified server-side via a signed JWT session.",
      "The entire UI is built for mobile-first use, with optimistic updates throughout the admin dashboard so actions feel instant. The public-facing page is intentionally minimal — no footers asking for ratings, no cookie banners, no distractions.",
    ],
    highlights: [
      "Zero user accounts — no signup, no login, no email required from respondents",
      "No IP addresses, names, or fingerprints stored — anonymity is architectural, not a promise",
      "Password-protected admin dashboard with JWT session cookies",
      "Admin password stored only in environment variables — never exposed to the frontend",
      "Create, edit, activate/deactivate, and delete questions from the dashboard",
      "View all anonymous responses grouped per question with response counts",
      "Delete inappropriate responses without affecting others",
      "Optimistic UI updates — admin actions reflect instantly before server confirmation",
      "Paginated public question list with staggered animations",
      "Mobile-responsive design with iOS Safari zoom prevention",
      "PostgreSQL backend with a single-query grouped response fetch for performance",
      "Built solo — full-stack, from schema to UI",
    ],
    link: "https://nacos.modred.dev/",
    github: "https://github.com/Modred14/nacos-ngl",
    img: "/nacos-feedback.png",
  },
  {
    slug: "valentine-web-generator",
    name: "Valentine Web Generator",
    tagline: "Personalised love, delivered digitally.",
    stack: [
      "Next.js",
      "JavaScript",
      "React",
      "Firebase",
      "Node.js",
      "Cloudinary",
      "Resend",
      "Tailwind CSS",
      "Lucide React",
    ],
    about:
      "Valentine Web Generator is a web platform for generating personalised Valentine pages with music, memories, and heartfelt messages.",
    description: [
      "This project started as a fun side experiment and turned into something thousands of people used to surprise their partners on Valentine's Day.",
      "Users fill out a short form — adding photos, a playlist, and a personal message — and the app generates a beautiful, shareable micro-site in seconds.",
      "Cloudinary handles image optimisation and storage, Resend powers the email delivery of the generated link, and Firebase stores each unique Valentine page persistently.",
    ],
    highlights: [
      "Dynamic page generation from user input in under a second",
      "Cloudinary integration for fast, optimised image uploads",
      "Resend-powered email delivery of shareable Valentine links",
      "Background music playback tied to the generated page",
      "Firebase real-time database for persistent page storage",
      "Mobile-first design with smooth animations and transitions",
    ],
    link: "https://hehe-hmm.netlify.app/",
    github: "https://github.com/Modred14/val-app",
    img: "/val-app.png",
  },
];
